### ISSUE TITLE
Destroys external links

### ISSUE THREAD

**Issue by kristofzerbe** [liolok/hexo-asset-link#3]
This plugins helps me a lot to reference images as it is done in Markdown by default, but actually it destroys external links. 

Markdown:  ``[Markdown](https://en.wikipedia.org/wiki/Markdown)``
Generated HTML:  ``<a href="https://myblog/categories/Tools/my-post/en.wikipedia.org/wiki/Markdown">Markdown</a>``

So, no external link is working anymore.

**Comment by kristofzerbe** [comment]
Found a typo in your code: Line 22 => protocal ... name it protocol and it should work.

**Comment by liolok** [comment]
Huge thanks! I'm gonna check on your PR right now.
