### ISSUE TITLE
External link is destroyed If external url include the asset_dir_name. 

### ISSUE THREAD

**Issue by watahani** [liolok/hexo-asset-link#6]
There is same issue with #3.
External link is destroyed If external url include the asset_dir_name. 

ex) 
post permalink: http://myblog.example.com/subdir/
asset_dir_name: post-title

> \[Markdown](http://example.com/post-title/hoge)

will be converted

> \<a href="http://example.com/subdir/post-title/hoge">

It seems that before the commit 137860db06f918430446c3d30d8ce0173ffba6a9 the external link might be ignored.

**Comment by watahani** [comment]
I've modified the code as follows as a tentative, but it looks not simple.
https://github.com/watahani/hexo-asset-link/commit/107a595c8a683accde4ba5eaa28a0b9e62237f09

**Comment by liolok** [comment]
Sorry for the delay, do you still need a fix up to now?

**Comment by watahani** [comment]
@liolok 
Thank you for your reply. Yes, I am still facing this issue.

**Comment by liolok** [comment]
Should be fixed with [this commit](https://github.com/liolok/hexo-asset-link/commit/c6d038757283d3f7e1953d3d7645d11d2bd617a2), I'll release 2.1.0 if it passes your use case test.

**Comment by watahani** [comment]
@liolok 
It works fine for me. Thank you so much!
