### ISSUE TITLE
look_behind does not match whitespace

### ISSUE THREAD

**Issue by botbotty** [liolok/hexo-asset-link#9]
https://github.com/liolok/hexo-asset-link/blob/a73cc261b1a9f50bc3e9519409e512d8ffe9c40f/index.js#L15-L16

`look_behind` will eventually turn into a regexp that matches the letter "s" instead of a whitespace, it should be `'(?<=[\(<\\s])'`.

Test in node:

```javascript
> let re1 = RegExp('(?<=[\(<\s])(.+)', 'g');
undefined
> let re2 = RegExp('(?<=[\(<\\s])(.+)', 'g');
undefined
> str=" hello", [str.match(re1), str.match(re2)];
[ null, [ 'hello' ] ]
> str="shello", [str.match(re1), str.match(re2)];
[ [ 'hello' ], null ]
```

**Comment by liolok** [comment]
Sorry for the delay.

Fixed at a8e212ac174284bf43f554ca8f2e984c1e5b9114
